Bloging/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

# 配置app的url
urlpatterns += [
    path('article/', include('article.urls', namespace='article')),
    path('err/', include('err.urls', namespace='err')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^', include('userprofile.urls', namespace='first_open')),
]

err/urls.py
# 引入path
from django.urls import path
# 本地模块
from err import views

# 正在部署的应用的名称
# Django2.0之后，app的urls.py必须配置app_name，否则会报错

app_name = 'err'

urlpatterns = [
    # 目前还没有urls
    path('not_found_404/', views.err_404, name='err_404'),
    path('wrong_method/', views.err_method, name='err_method'),
    path('no_right/', views.err_no_right, name='err_no_right'),

]

userprofile/urls.py
from django.conf.urls import url
from django.urls import path
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='userprofile_login'),
    path('logout/', views.user_logout, name='userprofile_logout'),
    path('register/', views.user_register, name='userprofile_register'),
    path('delete/<int:id>/', views.user_delete, name='userprofile_delete')
]

urlpatterns += [
    url(r'^$', views.user_login, name='userprofile_first_open'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save
# 引入信号接收器
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
    """User信息拓展模型"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField()
    # todo 密码md5加密
    password = forms.CharField()


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = {'username', 'email'}
        # fields = {'username', 'email', 'is_active', 'is_staff', 'date_joined', 'first_name', 'last_name', 'last_login'}

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get("password2"):
            return data.get('password')
        else:
            # todo Ajax动态加载
            raise forms.ValidationError('密码不一致请重新输入')

userprofile/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegisterForm


# Create your views here.
def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("article:article_list")
            else:
                # todo 使用ajax实现页面内校验, 返回来时页面
                return redirect('article:article_list')
    elif request.method == "GET":
        if request.session:
            return redirect('article:article_list')
        else:
            user_login_form = UserLoginForm()
            context = {'form': user_login_form}
            return render(request, 'userprofile/login.html', context)
    else:
        return redirect('err/err_method')


def user_logout(request):
    logout(request)
    return redirect("article:article_list")


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            # todo 返回来源页面
            return redirect('article:article_list')
        else:
            # todo Ajax动态加载
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'user_register_form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return redirect('err/err_method')


@login_required(login_url='/userprofile/login/')
def user_delete(request, user_id):
    """高危操作谨慎使用"""
    user = User.objects.get(id=user_id)
    if request.user == user:
        logout(request)
        # todo 此处可以设置为用户状态改变
        user.delete()
        return redirect('article:article_list')
    else:
        return redirect("err:no_right")

templates/userprofile/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
    <style>
        .col-12 {
            position: relative;
            float: contour;
            width: 100%;
            min-height: 1px;
            padding-right: 15px;
            padding-left: 15px;
            max-width: 38.2%;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <h5>还没有账号？</h5>
                <h5>点击<a href='{% url "userprofile:userprofile_register" %}'>注册账号</a>加入我们吧！</h5>
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="form-group col-md-4">
                        <label for="username">昵称</label>
                        <input type="text" class="form-control" id="username" name="username" required><!--required属性使该字断必须填写-->
                    </div>

                    <div class="form-group col-md-4">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>

                    <div class="form-group col-md-4">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>

                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}