Bloging/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

# 配置app的url
urlpatterns += [
    path('article/', include('article.urls', namespace='article')),
    path('err/', include('err.urls', namespace='err')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^', include('userprofile.urls', namespace='first_open')),
]

article/urls.py
# 引入path
from django.urls import path
# 本地模块
from article import views

# 正在部署的应用的名称
# Django2.0之后，app的urls.py必须配置app_name，否则会报错

app_name = 'article'

urlpatterns = [
    # 目前还没有urls
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
]

err/urls.py
# 引入path
from django.urls import path
# 本地模块
from err import views

# 正在部署的应用的名称
# Django2.0之后，app的urls.py必须配置app_name，否则会报错

app_name = 'err'

urlpatterns = [
    # 目前还没有urls
    path('not_found_404/', views.err_404, name='err_404'),
    path('wrong_method/', views.err_method, name='err_method'),
    path('no_right/', views.err_no_right, name='err_no_right'),

]

userprofile/urls.py
from django.conf.urls import url
from django.urls import path
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='userprofile_login'),
    path('logout/', views.user_logout, name='userprofile_logout'),
    path('register/', views.user_register, name='userprofile_register'),
    path('delete/<int:id>/', views.user_delete, name='userprofile_delete')
]

urlpatterns += [
    url(r'^$', views.user_login, name='userprofile_first_open'),
]

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'md_css/monokai_codehilite.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'self/self.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.cooper.com 2018</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                {# todo 添加更多入口 #}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">个人空间</a>
                            <a class="dropdown-item" href="{% url 'userprofile:userprofile_logout' %}">退出登录</a>
                            <a class="dropdown-item" href="#">设置</a>
                            {# todo 删除用户放在设置中更合适 #}
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                        </div>
                    </li>
                {% else %}
                    <!-- 如果用户未登录，则显示 “登录” -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:userprofile_login' %}">登录</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <script>
                        function user_delete() {
                            // 调用layer弹窗组件
                            layer.open({
                                title: "确认删除",
                                content: "确认删除用户资料吗？",
                                yes: function (index, layero) {
                                    location.href = '{% url "userprofile:userprofile_delete" user.id %}'
                                },
                            })
                        }
                    </script>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>